name: Renovate
on:
  schedule:
    - cron: '0 8-18 * * 1-5' # Every hour, between 08:00 and 18:00, Monday through Friday
jobs:
  renovate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.0.0
      - run: 'echo "{\"repositories\": [\"${GITHUB_REPOSITORY}\"]}" >renovate-self-hosted-config.json'
      - run: cat renovate-self-hosted-config.json
      - name: Self-hosted Renovate
        uses: renovatebot/github-action@v31.22.0
        with:
          configurationFile: renovate-self-hosted-config.json
          token: ${{ secrets.RENOVATE_TOKEN }}
